### ISSUE TITLE
Failed to create or merge pull request: HttpError: Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}

### ISSUE THREAD

**Issue by tairosonloa** [tgymnich/fork-sync#100]
Since a few days ago, I'm getting this error message. Here is the debug trace:

![Captura de pantalla 2022-07-11 011831](https://user-images.githubusercontent.com/14878189/178165852-b896f280-7978-4fc1-866f-2aedb4230617.png)

```yaml
name: "Sync with original repo - action"
#https://github.com/marketplace/actions/fork-sync

on:
  schedule:
    - cron: '0 16 * * 1,4'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: mikecao
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          head: master
          base: production
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
```

[Link to repo](https://github.com/tairosonloa/umami)
