### ISSUE TITLE
Won't automerge the PR. HttpError: Unprocessable Entity: "Can not approve your own pull request"

### ISSUE THREAD

**Issue by tairosonloa** [tgymnich/fork-sync#46]
Hi! First thanks for your job. I'm facing a strange issue here that I cannot get rid of. I finally achieved to get the workflow running as it is creating a PR to Sync the repo. However, PR won't be automerged and the GitHub Actions will fail. I tried two different configs, with different errors:

Config 1:
```yml
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: mikecao
          token: ${{ secrets.GH_PERSONAL_TOKEN }} # with public repo access
          head: master
          base: production
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
```

Error 1:
```
Run tgymnich/fork-sync@v1.4
  with:
    owner: mikecao
    token: ***
    head: master
    base: production
    merge_method: merge
    pr_title: Fork Sync
    auto_approve: true
request failed after 4 retries with a delay of 60
Error: Failed to create or merge pull request: HttpError: Unprocessable Entity: "Can not approve your own pull request"
```

---------
Config 2:
```yml
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: mikecao
          token: ${{ secrets.GITHUB_TOKEN }} # not my personal token
          head: master
          base: production
          merge_method: merge
          pr_title: Fork Sync
```

Error 2:
```
Run tgymnich/fork-sync@v1.4
  with:
    owner: mikecao
    token: ***
    head: master
    base: production
    merge_method: merge
    pr_title: Fork Sync
    auto_approve: false
request failed after 4 retries with a delay of 60
Error: Failed to create or merge pull request: HttpError: Unprocessable Entity: "Can not approve your own pull request"
```
--------------
Do you know what could be the problem? If it is about a misconfiguration from my side, I will be happy to open a PR updating the documentation when I realize of my error.

Owner repo: https://github.com/mikecao/umami
My repo: https://github.com/tairosonloa/umami (you can see there some manually closed PR that the GitHub Action created while I was testing)

**Comment by tairosonloa** [comment]
I currently don't have any branch protection rules (although I plan to add them). It seems like with config 1, my user is creating and trying to approve the PRs, while with config 2 the PRs are being created and tried to be approved by `github-actions` bot.

Shouldn't it be different users as @R0Wi  told in #24 ?

**Comment by R0Wi** [comment]
HI @tairosonloa if i remember correctly we introduced two new options in https://github.com/tgymnich/fork-sync/pull/24. One is the `auto_approve` option, the other one is the `personal_token` which i thing you're missing. So i think the user from `token` will open the PR while the user behind `personal_token` will auto approve it. Usually you will put the GitHub Actions token into `token` and some personal token with appropriate access (from another user) into `personal_token` and set `auto_approve` to true.

**Comment by R0Wi** [comment]
@tgymnich if i can help somehow in fixing this just let me know 👍

**Comment by tairosonloa** [comment]
The following config is working, as you suggested:

```yml
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: mikecao
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          head: master
          base: production
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
```
